engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- "spec/jasmine-2.5.2/"
- "spec/inverted-index-test.js"
- "spec/tests/test-spec.js"
- "gulpfile.js"
- "karma.conf.js"

