engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- "jasmine/"
 - "src/"
- "gulpfile.js"